### ISSUE TITLE
Unable to rename road file

### ISSUE THREAD

**Issue by jmcaffee** [creadri/LazyRoad#1] opened 2011-09-27 20:26 UTC
After renaming road file (Test1.ser to SubwayTunnel.ser), the road file is not listed in the list produced by /road
I did reload (both via the server and the client) with /reload after renaming with no difference in the list output.

After I renamed the file back to the original name it was created with (Test1.ser) and did a /reload, the road was listed as Test1

**Comment by creadri** [comment] 2011-09-29 11:03
I've tested renaming files and works great without glitches. Are you sure you didn't copy the file or something like that?

I can't reproduce that "bug", either with /road reload or /reload command.

**Comment by wolfwoodbrbu** [comment] 2012-03-31 23:30
Closing old fixed issues.

**Closed as completed by wolfwoodbrbu** 2012-03-31 23:30 UTC
